### ISSUE TITLE
getting c2 was not reachable error while adding c2 

### ISSUE THREAD

**Issue by kishore9030** [pucarasec/zuthaka#2]
while adding c2 im getting below error
![Screenshot 2021-09-06 104122](https://user-images.githubusercontent.com/77776738/132164219-7799e63e-a14d-4d6b-b1b2-dc5692c62499.jpg)
![Screenshot 2021-09-06 104122](https://user-images.githubusercontent.com/77776738/132164228-f1e7d8b0-d1d7-48ae-a883-072bef008909.jpg)

**Comment by kishore9030** [comment]
help me out of this

**Comment by lbonastre** [comment]
Hello! Is your infrastructure up and running?
The proposed [integration for Covenant](https://github.com/pucarasec/zuthaka/tree/main/ClassHandlers/Covenant) that you are using connects to the API of Covenant to create and parse the requests.
Please make sure your infrastructure is up and runnning

**Comment by kishore9030** [comment]
Yes it is up and running and I installed all dependencies but still.im getting same error and I'm using ubuntu 20 on Oracle virtual box .

**Comment by lbonastre** [comment]
Please consider that after the instantiation of Covenant you need to set up its password. By navigating to the management interface of Covenant.

For further information about what is happening in Zuthaka you can activate  the frontend's log (to be shown in the developer's console):
![Front-end logging](https://user-images.githubusercontent.com/67699625/132402386-5c7d7b49-05b9-4f05-95ad-5b304f213d95.PNG)

Additional backend's log information can be obtained by uncommenting the lines 266 and 272 on the file:
file name: src/zuthaka/zuthaka/settings.py 
```
263     'loggers': {
264         'django': {
265             'handlers': ['console'],
266             'level': 'DEBUG',
267             'propagate': True,
268             'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO')
269         },
270         'backendapi': {
271             'handlers': ['file'],
272             'level': 'DEBUG',
273             'propagate': True,
274             'level': os.getenv('DJANGO_LOG_LEVEL', 'DEBUG')
275         },
```

This information will be outputed to the docker-compose log:
![back-end logging](https://user-images.githubusercontent.com/67699625/132403391-a03383d6-5ff9-481a-9db0-8f9860bd596f.PNG)

**Comment by kishore9030** [comment]
Thanks .  😊 for u r support.  Its working.
