### ISSUE TITLE
Default credentials don't  work on Zuthaka interface

### ISSUE THREAD

**Issue by ghost** [pucarasec/zuthaka#3]
Hi team,

After installing the application with Docker, when entering on the Zuthaka interface with the default credentials, the application returns an error message. Please check the attached screenshots:

![11-7-2022 5-02-45 PM](https://user-images.githubusercontent.com/63946864/200407039-cc958d9b-94ae-4298-84cf-ddedc9d6cf4a.png)
![11-7-2022 5-07-05 PM](https://user-images.githubusercontent.com/63946864/200407072-6e333937-7001-46a5-8037-30db3eac5658.png)

Thanks

**Comment by Ycix** [comment]
What is the correct password?

**Comment by lbonastre** [comment]
Correct credentials are pucara:zuthaka_project

on the other hand, the problem was produced by the reference of the backend compiled to the frontend application. it was solved on commit: e87be50461712d31da37122fabf8bc100a78c538

**Comment by ghost** [comment]
Hi team,

Now the Zuthaka interface is working with the default credentials.
Great job
